spring:
  datasource:
      url: jdbc:mysql://localhost:3306/yuanli?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: yuanli
      driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: warn
    com.yl.mapper: trace
  pattern:
    console: '%p%m%n'